### ISSUE TITLE
GenereatedAppGlideModuleImpl is implemented incorrectly. If you're manually implemented this class, remove your implementation. The annotation processor will generate a correct implementation.

### ISSUE THREAD

**Issue by Maharshi01** [MappCloud/React-native-plugin#1]
Hi Aleksander,

This is Maharshi, I noticed we have an issue with glide version mismatch. After integrating the plugin, i tried to access screens which use the 'react-native-fast-image' for displaying the images. Then this error is showing up in those screens, after a bit of debugging I noticed that it's an issue with the glide version mismatch with the react-native-mapp-plugin and react-native-fast-image(v7.0.2) packages. Please let me know the ideal solution to resolve this. I have attached the screenshots for your reference. 

![Screenshot_20210601-204128](https://user-images.githubusercontent.com/48430425/120416331-9b11e600-c37a-11eb-965a-e1709808d321.png)

![Screenshot 2021-06-02 at 8 05 26 AM](https://user-images.githubusercontent.com/48430425/120416638-1c697880-c37b-11eb-95ff-8a466008e96a.png)

![Screenshot 2021-06-02 at 8 05 56 AM](https://user-images.githubusercontent.com/48430425/120416645-1e333c00-c37b-11eb-8a20-1e956f650f3d.png)

![Screenshot 2021-06-02 at 8 06 09 AM](https://user-images.githubusercontent.com/48430425/120416651-1f646900-c37b-11eb-945a-bd91f3820585.png)

P.S: MAPP is using 4.11.0 and fast-image 4.9.0.

**Comment by acamarinkovic** [comment]
Hi Maharshi, We can downgrade the version of the library. But the master version of this library uses the same glide. So if you can pls update the fast-image library if not then we will downgrade...
  https://github.com/DylanVann/react-native-fast-image/blob/master/android/build.gradle

**Comment by acamarinkovic** [comment]
The version is live so pls try latest one 1.0.3-beta7

**Comment by Maharshi01** [comment]
After upgrading the package, the issue has been resolved. Thanks @acamarinkovic
