### ISSUE TITLE
con.mapp.rich_message_received is not a supported event type for RNMappEventEmitter

### ISSUE THREAD

**Issue by Maharshi01** [MappCloud/React-native-plugin#3]
Hi Aleksander,

I have upgraded the package to the latest version i.e., 1.0.3-beta8 and after that the crash issue was resolved when i call deeplinklistener.bt I'm facing one more issue in iOS when i call addPushListener in iOS. I think the issue is because of typo in Mapp.js and for android in PushNotificationEvent.java files . I have attached the screenshot for your reference..

![Screenshot 2021-07-01 at 9 41 46 PM](https://user-images.githubusercontent.com/48430425/124159117-6350a800-dab8-11eb-851d-0c4ba60b5ef0.png)

![Screenshot 2021-07-01 at 9 41 57 PM](https://user-images.githubusercontent.com/48430425/124159128-65b30200-dab8-11eb-8a07-a5322749eda0.png)

**Comment by acamarinkovic** [comment]
OK thank you for the report. I will publish new version with this fix during the day

**Comment by acamarinkovic** [comment]
pls try with 1.0.3-beta9

**Comment by Maharshi01** [comment]
Will check and let you know, Thanks :)
