### ISSUE TITLE
Execution failed for task ':react-native-mapp-plugin:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by Maharshi01** [MappCloud/React-native-plugin#4]
Hi Aleksander, 

After updating the package to the latest version i.e., 1.0.3-beta8. I'm unable to run the code in android because of the following issue. It's because of the missing declaration in the manifest i guess. Can you please help to solve this issue cause i couldn't test the listeners in android using the  latest package. Thanks.

![Screenshot 2021-07-01 at 9 53 18 PM](https://user-images.githubusercontent.com/48430425/124159939-57191a80-dab9-11eb-8cf7-ce97f6a302ed.png)

**Comment by acamarinkovic** [comment]
Are you planning to use geolocation? This is related to the target version of the android application

**Comment by acamarinkovic** [comment]
pls try with 1.0.3-beta9

Now geo permission is disabled but you can use geo if provide permission before that.

**Comment by Maharshi01** [comment]
Okay, Noted. Will check and let you know, Thanks :)
